import type { Metadata } from "next";
import { Roboto_Condensed, EB_Garamond } from "next/font/google";
import "./globals.css";
import { QueryProvider } from "@/components/providers/query-provider";
import { Toaster } from "sonner";
import NextTopLoader from "nextjs-toploader";
import Script from "next/script";

const robotoCondensed = Roboto_Condensed({
  variable: "--font-roboto-condensed",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

const ebGaramond = EB_Garamond({
  variable: "--font-eb-garamond",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        ></meta>
        {/* // eslint-disable-next-line @next/next/no-sync-scripts */}
        <Script
          src="https://sandbox.doku.com/jokul-checkout-js/v1/jokul-checkout-1.0.0.js"
          strategy="afterInteractive"
        />
      </head>
      <body
        className={` ${ebGaramond.variable} ${robotoCondensed.variable} antialiased`}
      >
        <NextTopLoader
          color="#003077"
          showSpinner={false}
          height={3}
          shadow={false}
          speed={200}
        ></NextTopLoader>
        <QueryProvider>{children}</QueryProvider>
        <Toaster position="top-center"></Toaster>
      </body>
    </html>
  );
}
